# Generated by Django 2.1.7 on 2019-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190327_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_banner_image',
            field=models.ImageField(default='', upload_to='./banner'),
        ),
    ]
