# Generated by Django 2.1.7 on 2019-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_product_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_banner_image',
            field=models.ImageField(default='', upload_to='../banner'),
        ),
    ]
